### ISSUE TITLE
Documentation  Todo

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/unfold#43]
- [x] Remove Permalink Icon
- [ ] Fix some formation issues  for autodoc (e.g. uf_addmarginal)
- [ ]  code-examples in API should be code-block style, then you can ctrl+c + ctrl+v out of it.
- [x]  Change Tutorial 3 subject to subject 11
- [x] move website privacy to footer

**Comment by behinger** [comment]
- [ ] there are some brackets that need removing e.g. color(), customField() e.g in "data structures"

**Comment by behinger** [comment]
A table with alternative toolboxes would be great. The more I read & know the lingo, the more toolboxes I find.

active toolboxes:

matlab: mTRF toolbox got a big update - have to look at it
python: https://github.com/christianbrodbeck/eelbrain - has lots of statistics options, find it under reverse-correlation
mne-python: check the development, but afaik not much development there
unfold.jl obviously

With various different pros/cons. 
-I.e. unfold is strong on intuition (e.g. only one with formula interfaces), easy combination of TRF + rERP, only one with non-linear effects
- unfold.jl is strong due to same syntax for mass univariate, deconv, with&without mixed model. Potentially speed at a later stage
- mTRF is great at backward+forward encoding (i.e. "decoding" analyses) and everything cross-validated.
- eelbrain seems great at performing the accompanying stats
- mne-python has a whole ecosystem for preprocessing, thus might be comfortable to stay in that "land"

**Comment by behinger** [comment]
I found a student who will have a look at some of the above points and document stuff :)
- [ ] rerun all tutorials, check that you can at least run them all
- [ ] fix (and/or write a list) what is unclear in the tutorials
- [ ] fix inconsistencies in Function Documentation (scroll through "Function Documentation", e.g. https://www.unfoldtoolbox.org/unfold.html#src.uf_toolbox.uf_designmat_addcol has some kind of problem that needs fixing
- [ ] write a FAQ, in the issues we have some tickets labelled as FAQ, put them all together in a new sphinx file:
`unfold/docs/docs_sphinx/faq.rst`
